In [1]:
import os

import netbios
import pandas as pd
from pandas import DataFrame
from scipy.stats import zscore
import numpy as np
from numpy import mean
from numpy import std
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold
from matplotlib import pyplot
from itertools import combinations
from pandas import DataFrame
from sklearn.preprocessing import PolynomialFeatures
from sklearn.ensemble import GradientBoostingRegressor
import lightgbm as xgb
from lightgbm import LGBMRegressor
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
from sklearn.model_selection import RepeatedKFold
from numpy import absolute
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
v1 = pd.read_excel("new_dataset_1.xlsx")
v3 = pd.read_excel("new_dataset_3.xlsx")
v4 = pd.read_excel("new_dataset_4.xlsx")
v5 = pd.read_excel("new_dataset_5.xlsx")
v6 = pd.read_excel("new_dataset_6.xlsx")

vavg = pd.concat([v1, v3, v4, v5, v6]).groupby(level=0).mean()
vavg

     pock_volume  pock_volume_st  pock_asa  pock_asa_st  pock_pol_asa  \
0       216.1078        121.2786  140.5950      77.3994       82.4008
1       226.9004        121.7804  143.9734      76.3840       82.8320
2       449.8378        148.1168  284.7686      85.9594      166.1374
3       431.3610        133.9748  266.0926      77.3620      147.4218
4       423.0178        150.4954  269.0508      89.1756      150.1200
5       466.8630        127.0670  290.0514      74.3042      159.1102
6       486.9560        132.7076  305.5394      78.1218      172.6528
7       414.6304        143.8162  264.4642      85.2280      149.3912
8       417.8214        131.2300  271.5506      78.1208      150.9268
9       241.9776        132.5872  158.4538      82.6856       87.9498
10      233.3860        112.6938  143.4378      68.7232       74.7644
11      290.4110        145.6226  180.4276      89.8294      100.6208
12      240.4212        118.4624  152.2506      76.0182       82.5750
13      248.8552        121.3944  157.0986      76.0182       89.6538
14      228.1230        124.2290  148.2056      77.5268       82.6990
15      242.8188        133.9940  156.8424      84.9650       84.9842
16      207.2474        126.1238  135.0662      80.7986       80.5584
17      247.5600        142.7158  159.3968      89.0404       90.2484
18      264.4950        132.5530  166.1234      81.8712       91.6012
19      229.5316        141.6248  149.0052      91.3628       83.0900
20      239.1818        130.2358  149.1998      81.2430       85.4072
21      242.9664        122.3634  155.2756      74.9594       90.3754
22      205.6132        124.5160  132.5706      81.2374       74.9962
23      236.4240        145.8732  151.6604      87.9220       86.3952
24      234.0618        118.7616  148.7580      74.6324       81.9046
25      225.3318        138.3526  149.1992      88.6196       86.2848
26      244.8986        127.9154  159.0896      80.8448       95.6904
27      256.0684        119.8648  167.3556      79.3200       92.1950
28      423.0498        132.8566  262.8868      79.1474      136.5256
29      403.0806        128.7818  254.1960      76.5788      151.0618
30      394.7098        141.4074  252.4592      84.2474      139.6194
31      429.3998        142.6736  265.4494      81.9134      145.6598
32      432.7304        138.2428  272.6596      81.1434      153.7002
33      453.4300        135.8082  288.3008      80.2222      168.8232
34      465.6250        135.8756  305.7942      81.4702      171.1564
35      422.7702        140.2758  263.0574      83.9910      142.1542
36      432.2062        139.7586  277.8680      82.5340      153.6400
37      453.6720        144.3614  282.3748      84.3006      153.5056
38      451.4090        146.3574  277.4562      86.6530      156.0986
39      389.9328        162.2156  258.3216      98.4094      155.6750
40      456.9016        132.8856  291.3836      79.3952      165.4048
41      448.9240        129.8648  284.8182      77.4310      161.7472
42      388.4478        141.2288  257.0808      85.6676      149.7584
43      458.2094        138.8814  284.7730      81.4758      153.7176
44      385.5676        136.1064  246.2420      82.3140      134.9256
45      402.7328        140.3046  251.8214      81.6754      138.4390
46      454.4484        140.9534  282.6242      82.9988      165.7614
47      449.5948        133.8756  285.3482      77.8400      170.3934
48      412.1204        141.7732  262.3546      86.0906      155.8366
49      465.0896        135.9258  299.0884      80.9618      161.3180
50      407.0160        137.6520  260.4816      82.8762      159.2424
51      396.9578        137.6728  248.8250      79.7228      136.0710
52      411.4934        135.2764  254.5464      79.0800      140.8246
53      454.1602        124.2434  289.2096      72.9904      165.2934
54      464.9488        141.4742  290.3418      83.1598      161.3204
55      414.9574        147.1564  263.3168      86.2992      146.5520
56      435.8508        143.9298  263.2192      82.1732      151.3974
57      454.3930        136.0074  285.0314      80.0856      164.1492
58      432.1938        131.6228  283.2306      80.9688      167.7320
59      356.1778        136.9118  230.4536      83.4350      127.0108
60      454.5476        131.8126  293.1228      82.6828      167.7842
61      448.4108        127.7026  285.6784      75.5940      174.0220
62      437.9852        142.3790  280.7250      86.7874      160.4474
63      430.3904        140.0806  272.5850      81.8640      152.6410
64      427.0312        135.0904  269.9054      79.9112      155.1536
65      389.7484        147.2124  241.5858      85.8856      132.5264
66      456.7638        142.1890  289.4584      84.8270      164.9400
67      440.4428        125.5648  287.2394      74.5632      170.5286
68      388.4392        141.8232  250.0306      89.9154      144.5538
69      412.9482        136.4412  255.9134      81.4096      143.6356
70      448.9804        137.1538  276.0992      80.2130      145.1362
71      410.8544        163.8116  273.6848      97.6410      154.6748
72      466.9708        133.6120  292.7546      79.8072      172.2104
73      396.5782        131.2798  249.8778      75.8232      144.4762
74      454.6864        137.1872  277.4636      79.9786      150.0616
75      393.2336        141.1384  244.6854      82.7794      142.0980
76      386.9000        130.1102  237.0946      74.4824      135.9688
77      419.5902        131.7482  254.7040      76.7864      135.9924
78      447.8950        129.7542  289.4980      77.6440      162.5276
79      466.7832        133.9768  292.6830      80.1164      168.8090
80      435.1892        138.0050  282.9246      84.7352      164.8616
81      436.9112        132.0164  279.3758      80.4924      154.6980
82      487.1986        150.9028  313.2856      91.6710      182.3278
83      436.9284        130.7054  273.7890      77.0640      159.1726
84      438.4004        140.5486  278.3046      84.6898      165.5874
85      452.1034        130.5850  293.7676      77.1170      180.7156
86      462.2318        134.7678  289.6348      79.4454      161.4408
87      436.8780        140.0058  271.8530      83.4356      154.5408
88      481.2754        147.7194  293.1514      84.3274      158.9674
89      372.7822        140.3746  233.7430      86.8382      135.8844
90      471.5074        142.7272  295.4116      82.8010      172.8114
91      439.8808        133.4526  281.4932      77.8916      162.6850
92      470.9362        138.9372  287.3036      79.9578      165.4484
93      445.4624        133.3404  285.3902      80.3800      177.0818
94      443.5394        132.8366  279.5256      76.8958      162.3196
95      392.6844        137.0470  257.7762      83.1302      144.7368
96      458.8628        127.7498  293.7546      76.1048      172.8278
97      415.8626        135.2836  268.2222      83.6740      158.0450
98      474.7016        123.1634  300.9600      69.1390      182.1858
99      233.5156        123.9948  148.7606      77.9048       88.4576
100     234.2670        131.4830  156.3694      82.3994       92.5142
101     238.1640        120.8942  160.4146      79.2538       99.1382
102     224.6554        130.3976  140.8772      81.3528       75.9906
103     268.9598        141.8312  180.4778      92.1394      102.1776
104     258.1156        118.8596  166.3708      76.9694       97.9842
105     214.8550        127.1580  132.9908      77.2028       76.6938
106     228.8914        124.0632  149.1950      80.7100       80.0874
107     209.4502        143.0470  137.0912      90.4490       78.3200
108     219.2234        131.6162  146.8192      84.0958       82.3334
109     241.8448        110.4604  155.9262      68.0664       89.9174
110     229.4930        122.7528  148.6148      78.1618       85.6356
111     259.5272        133.2660  173.3452      87.0614      101.0736
112     243.8498        126.4214  155.8030      79.3946       80.1520
113     240.7136        137.3328  154.2832      86.5996       81.2388
114     219.5876        119.1972  139.4552      75.9002       78.2382
115     195.9358         98.5038  124.8862      63.3808       65.9910
116     227.8810        121.0740  154.6134      78.0820       96.0734
117     213.5944         98.5778  137.0878      63.0558       78.1188
118     226.0848        118.3742  147.0132      73.9450       84.1590
119     236.9968        111.6566  159.2996      73.0962       87.7798
120     185.4082         99.9470  117.9178      61.4530       61.4574
121     234.5004        140.2642  152.6700      88.1354       86.4746
122     258.9246        124.7232  168.3300      78.4160       90.0440
123     249.2816        129.0916  158.6064      82.1294       89.1552
124     222.5354        119.8038  145.4218      78.2802       83.7980
125     223.7036        140.3116  145.8276      87.7606       80.5626
126     189.5070        125.7914  123.8180      80.3340       68.2196
127     222.8014        133.7212  142.4524      82.5982       82.8146
128     199.1894        109.0012  124.1274      66.0040       69.8734
129     195.4364        123.2050  128.1656      78.1128       76.6330
130     219.2230        118.5868  140.9024      74.3772       74.5638
131     180.8496        147.4012  120.6384      90.8628       66.2418
132     208.3850        115.1940  136.5596      72.8052       74.2036
133     236.3672        132.6282  152.4402      81.1498       87.7056
134     240.7892        117.6354  150.8244      73.1942       83.0752
135     185.6818        132.5886  121.2426      82.7356       66.9032
136     200.7046        117.9808  132.9798      74.6514       74.3882
137     218.3054        128.1090  143.1686      81.5764       84.6060
138     200.1814        101.5566  126.2104      61.8048       65.7220
139     240.1974        133.1106  151.9406      83.6472       83.9430
140     257.2050        133.8408  168.4264      86.4718       96.1108
141     230.9156        117.4910  148.3458      76.1420       82.1132
142     199.1284        111.3424  125.8018      69.4284       75.9882
143     211.4460        121.4064  136.9116      77.2460       72.9934
144     223.5076        108.8844  141.4764      68.2786       81.2668
145     229.3456        126.7408  147.2584      79.8582       79.8456
146     239.2640        124.0872  153.2648      77.7058       84.6970
147     212.0258        135.4904  140.3140      85.2378       79.4890
148     231.6832        135.0256  150.6046      85.6660       87.1278
149     184.5932        124.2772  123.0634      81.9092       64.2282
150     212.2088        121.8868  140.0032      77.8096       74.3386
151     223.2064        118.7714  141.5322      76.0804       81.3952
152     212.2960        123.6632  136.5842      77.3970       73.4402
153     216.1352        126.0182  136.0994      77.6504       72.5092
154     226.4564        115.6518  146.7962      73.7000       85.8176
155     234.8136        123.5134  146.9180      77.2750       79.9594
156     223.1612        123.4424  152.9676      79.3634       87.1602
157     228.1162        121.3316  156.6356      80.6768       88.2316
158     192.9362        110.0684  123.3398      69.9452       66.4932
159     211.0720        114.7570  136.8784      73.6048       75.2110
160     238.2438        125.7358  151.0470      77.8826       85.8758
161     221.5434        130.2414  142.3328      83.3622       81.6608
162     241.3564        125.2652  155.0186      77.9718       88.4226
163     245.7118        120.0018  165.3826      79.4990      101.0778
164     240.1260        127.5572  158.8116      82.5898       89.1736
165     204.6714        115.5904  134.3372      73.2630       75.8226
166     227.3820        111.5870  145.4252      72.0510       82.3582
167     225.3520        126.0518  153.6772      83.0072       94.1546
168     250.1836        116.3352  161.0156      72.7922       81.5192
169     250.8164        131.3538  164.2746      83.0420       92.2918
170     210.9298        120.0054  137.6574      76.4376       83.3382
171     269.1768        136.1842  171.7294      85.2990       99.3198
172     216.4862        128.9612  144.2540      83.3148       87.1954
173     203.4970        112.8718  132.9338      68.4380       74.1508
174     183.0104        124.8534  115.5042      76.7812       63.4264
175     215.3788        127.0944  142.7024      80.4002       82.5932
176     245.4950        128.6818  162.5492      80.3374      100.1542
177     208.6446        133.9728  135.9132      85.0752       73.5028
178     256.0244        137.4442  165.2750      89.9772       98.0132
179     211.1806        126.2522  131.5178      79.0900       76.4840
180     263.2374        131.2414  172.0252      84.6450      105.1610
181     251.7956        133.4250  163.0850      84.4550       94.4320
182     338.7932        119.8526  213.3680      73.2322      116.8790
183     230.0980        119.2104  152.5536      73.2144       90.0568
184     203.9950        124.2824  134.6770      77.0550       81.4730
185     197.1798        131.4706  128.5936      83.2762       73.1032
186     228.1954        123.0886  151.1914      79.3226       86.7034
187     241.2290        137.7324  157.9882      88.3328       91.0992
188     236.6446        129.1412  150.2610      80.0502       85.9588
189     233.3476        138.5350  151.5604      87.1408       84.1762
190     218.8026        110.6842  142.6148      73.0394       81.8192
191     226.7034        127.3366  148.4186      80.8658       86.7880
192     222.4274        121.8792  141.6094      75.2922       82.8900
193     209.1390        119.8474  137.8154      75.3916       77.9420
194     205.6530        125.6306  129.7710      77.5306       73.7194
195     216.8804        124.7264  142.4076      80.4910       84.5196
196     160.6406        118.6232  103.6604      77.8260       60.9802
197     230.0246        129.1064  146.2250      80.1794       83.3260
198     216.4118        111.4658  146.2996      72.4570       87.3638
199     211.0912        130.0758  135.1088      81.4028       77.1994
200     249.0116        123.4454  160.6382      76.7116       94.5336
201     251.4066        134.5900  164.0882      86.1884       92.0696
202     217.5950        122.4846  140.5214      77.9078       80.2488
203     266.1542        132.2832  173.0486      84.2168       96.5450
204     213.5506        115.0282  131.2884      71.6912       74.8438
205     280.1904        123.9688  182.2276      77.7940      104.2208
206     231.8224        126.7834  152.4600      83.3036       90.3878
207     223.7286        118.5366  149.1448      76.7606       86.4442
208     241.9466        142.0656  159.3592      91.7590       93.2112
209     256.5800        129.0302  171.4538      77.8010       93.7654
210     227.4468        127.1732  144.8040      76.3974       79.6086
211     196.5330        133.5666  124.0116      82.5328       69.7764
212     177.8890        115.8184  119.6470      74.2088       66.5674
213     241.7594        131.1322  152.1946      80.5820       86.1942
214     178.5932        135.4460  118.9570      86.8134       71.5584
215     220.7904        112.2540  143.3798      71.5430       74.0798
216     202.0792        135.4870  132.6138      86.1062       78.5230
217     173.0556        119.9986  115.9458      77.3758       64.3956
218     234.0690        124.4822  152.8966      78.3322       86.4842
219     244.3858        138.7332  162.0762      86.7592       95.4470
220     274.5470        133.7176  181.8276      88.2712      101.4930
221     206.6546        126.3772  133.2404      79.2014       72.7958
222     282.4904        147.2910  178.2912      88.6326       93.7248
223     194.5516        127.6682  126.7828      83.0020       69.9706
224     224.0024        126.5038  143.9164      77.1240       82.3174
225     217.7448        129.3186  141.7110      81.7414       81.5392
226     262.5066        133.9934  169.4006      85.7280       95.2560
227     214.5474        134.3306  143.3982      88.2448       85.8668
228     218.8834        132.5154  147.1680      87.6794       86.5386
229     230.8186        130.1658  154.0480      89.0192       94.4172
230     207.5074        106.2856  138.3880      72.2290       83.7654
231     203.1678         97.2562  128.9136      62.5992       67.6900
232     216.1544        107.0958  135.0560      68.9802       77.9608
233     174.2290        135.9996  116.8336      87.7796       67.2686
234     213.6970        132.4690  142.6930      83.7990       86.5950
235     185.2824        124.8798  128.6334      83.2334       75.9288
236     211.6476        118.4572  136.4722      77.9772       77.8864
237     246.7336        118.4666  162.7996      74.5500       85.0204
238     260.6230        123.8278  167.9960      76.5694       98.6966
239     188.2518         97.2906  123.7934      63.7842       70.7298
240     249.3422        127.4960  159.9090      81.5434       83.2622
241     230.8276        131.0698  149.3118      82.2706       87.8662
242     219.2578        112.4836  143.0324      73.0814       80.1982
243     207.9992        115.7350  137.7482      71.0622       86.2256
244     206.6648        122.8198  130.4606      74.0522       71.7368
245     229.0816        123.3840  145.1398      77.3770       76.4826
246     175.9006        135.7910  116.2462      86.2020       70.5920
247     204.9606         99.8272  133.3364      64.4672       78.7042
248     185.6572        111.0662  120.3032      73.3612       70.2678
249     196.7564        119.2188  127.6546      74.7502       73.6704
250     249.4294        131.9972  157.8310      83.4852       92.3176
251     240.9032        139.3364  150.2186      84.2660       87.4944
252     236.8636        127.9546  154.5638      80.9858       85.9742
253     187.9148        124.7148  125.5900      79.4942       72.9968
254     205.9716        119.2882  135.0582      77.9488       80.8602
255     235.2178        135.5220  149.8500      83.6990       84.8654
256     261.5900        134.7720  169.0434      84.9664       94.3916
257     249.2788        137.4306  165.3998      87.0484       96.0736
258     187.2900        116.7086  121.0270      72.3834       67.3652
259     235.4022        127.7646  155.2034      82.8364       86.9868
260     216.0146        127.3262  137.6828      80.6632       77.3056
261     142.0746        108.3242   90.4604      70.5048       51.9558
262     245.4750        124.1606  160.5398      78.0490       87.6152
263     170.8380        115.9470  112.2500      76.0476       61.7016
264     250.1316        139.1414  162.3460      87.1950       89.6044
265     183.4602        123.8162  118.3246      77.2490       72.0046
266     248.7964        131.0846  159.0636      83.4116       89.1306
267     211.2534        136.2972  138.0340      87.0034       79.7710
268     246.3852        130.5926  154.9648      80.8188       82.5010
269     237.3276        127.9802  154.6114      79.2022       90.0372
270     201.3280        135.6924  132.7376      88.0578       79.3954
271     231.3104        120.1704  147.6320      75.0372       85.9578
272     166.2552        104.6648  107.4666      68.6514       61.5150
273     242.6514        118.7594  157.6050      76.6532       86.5664
274     227.0068        133.7402  144.7032      83.4996       82.9614
275     240.0956        126.3882  158.4734      81.5752       90.5162
276     199.8668        122.0476  128.6002      76.2604       69.5840
277     202.6292        125.3984  130.3664      79.4312       75.1902
278     282.8106        140.3410  180.6154      85.6488      103.9736
279     283.9706        127.1114  180.5010      77.2108      101.0090
280     351.0418        139.5432  216.8770      80.5314      123.8890
281     345.4014        145.9202  227.0990      87.9808      128.0844
282     362.6316        130.2036  232.6476      76.4564      133.9046
283     364.8300        141.6574  241.5496      88.0294      139.4086

In [3]:
vavg = vavg.drop(['DELTA30'], axis=1)

In [4]:
vavg.columns

Index(['pock_volume', 'pock_volume_st', 'pock_asa', 'pock_asa_st',
       'pock_pol_asa', 'pock_pol_asa_st', 'pock_apol_asa', 'pock_apol_asa_st',
       'pock_asa22', 'pock_asa22_st',
       ...
       'gravy', 'X.g', 'X.a', 'X.v', 'X.l', 'X.i', 'X.p', 'X.f', 'X.m', 'X.w'],
      dtype='object', length=126)

In [5]:
df = pd.read_excel('new_df_66.xlsx', engine='openpyxl')
seq_and_y = df.iloc[:, 128:]
vavg = pd.concat([vavg, seq_and_y], axis=1)
vavg.describe(include='all')

,pock_volume,pock_volume_st,pock_asa,pock_asa_st,pock_pol_asa,pock_pol_asa_st,pock_apol_asa,pock_apol_asa_st,pock_asa22,pock_asa22_st,pock_pol_asa22,pock_pol_asa22_st,pock_apol_asa22,pock_apol_asa22_st,nb_as,nb_as_st,mean_as_ray,mean_as_ray_st,mean_as_solv_acc,mean_as_solv_acc_st,apol_as_prop,apol_as_prop_st,mean_loc_hyd_dens,mean_loc_hyb_dens_st,hydrophobicity_score,hydrophobicity_score_st,volume_score,volume_score_st,polarity_score,polarity_score_st,charge_score,charge_score_st,prop_polar_atm,prop_polar_atm_st,as_max_dst,as_max_dst_st,convex_hull_volume,convex_hull_volume_st,nb_abpa,nb_abpa_st,ala,ala_st,arg,arg_st,asn,asn_st,asp,asp_st,cys,cys_st,gln,gln_st,glu,glu_st,gly,gly_st,his,his_st,ile,ile_st,leu,leu_st,lys,lys_st,met,met_st,phe,phe_st,pro,pro_st,ser,ser_st,thr,thr_st,trp,trp_st,tyr,tyr_st,val,val_st,rog_pro_noh,rog_pro_noh_sd,rog_pro_bb,rog_pro_bb_sd,rog_pro_ca,rog_pro_ca_sd,rog_bs_noh,rog_bs_noh_sd,rog_bs_bb,rog_bs_bb_sd,rog_bs_ca,rog_bs_ca_sd,rmsd_pro_noh,rmsd_pro_noh_sd,rmsd_pro_bb,rmsd_pro_bb_st,rmsd_pro_ca,rmsd_pro_ca_sd,rmsd_bs_noh,rmsd_bs_noh_sd,rmsd_bs_bb,rmsd_bs_bb_sd,rmsd_bs_ca,rmsd_bs_ca_sd,b_para,b_anti,h_3.10,halpha,h_pi,turn,bend,random.coil,ip,molecular.weight,aromaticity,instability,gravy,X.g,X.a,X.v,X.l,X.i,X.p,X.f,X.m,X.w,PP3.1,KF1.1,KF2.1,KF3.1,KF4.1,KF5.1,KF6.1,KF7.1,KF8.1,KF9.1,KF10.1,Z1.1,Z2.1,Z3.1,Z4.1,Z5.1,F1.1,F2.1,F3.1,F4.1,F5.1,F6.1,T1.1,T2.1,T3.1,T4.1,T5.1,VHSE1.1,VHSE2.1,VHSE3.1,VHSE4.1,VHSE5.1,VHSE6.1,VHSE7.1,VHSE8.1,ProtFP1.1,ProtFP2.1,ProtFP3.1,ProtFP4.1,ProtFP5.1,ProtFP6.1,ProtFP7.1,ProtFP8.1,ST1.1,ST2.1,ST3.1,ST4.1,ST5.1,ST6.1,ST7.1,ST8.1,BLOSUM1.1,BLOSUM2.1,BLOSUM3.1,BLOSUM4.1,BLOSUM5.1,BLOSUM6.1,BLOSUM7.1,BLOSUM8.1,BLOSUM9.1,BLOSUM10.1,MSWHIM1.1,MSWHIM2.1,MSWHIM3.1,DELTA30
count,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.00000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,3.120000e+02,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000
mean,295.621795,129.589187,189.283497,80.118408,107.643247,48.826742,81.640254,38.617612,103.073256,52.904097,61.011734,34.842510,42.061449,25.681874,82.510785,41.939647,3.093211,0.865267,0.385657,0.133696,0.159285,0.160638,12.022960,12.591963,11.604169,8.120404,2.880592,1.041781,6.314527,2.389755,1.121172,0.928679,39.367342,13.272286,7.149812,3.377145,49.976770,43.261601,5.419784,2.428500,0.037537,0.125613,0.220838,0.379858,0.037976,0.111674,0.477921,0.493272,1.286000,0.708298,1.024915,0.546975,0.024938,0.078965,1.219594,0.586696,0.601933,0.332799,0.009818,0.049747,0.021199,0.070471,0.800207,0.611256,0.011836,0.050308,0.675846,0.228065,0.025292,0.101210,1.906514,0.555192,0.497488,0.329857,0.019154,0.055326,0.700148,0.746837,0.31567,0.403601,16.947600,0.072105,16.317297,0.073829,16.321763,0.073146,7.243071,0.132868,7.793578,0.125405,7.439599,0.129418,1.698001,0.138384,1.206229,0.119615,1.175045,0.119885,1.357415,0.186421,0.889837,0.144379,0.856466,0.160705,0.008354,0.331783,0.024981,0.055357,0.000086,0.176876,0.139313,12.887642,5.136839,19620.048453,0.086983,58.281784,-0.350084,0.074696,0.063172,0.058780,0.073059,0.066147,0.067945,0.025249,0.038791,1.714286e-02,-1.770224,3.163590,-53.618301,2.929006,4.035032,-19.087564,-31.678654,1.303429,0.870385,-12.947885,-23.323077,19.098013,-103.104840,-15.542949,-88.797436,48.871026,-48.963692,-17.917359,-35.627244,59.324019,10.532429,-21.692035,-1072.155128,-38.518429,9.963974,39.331346,158.906026,-6.432532,-34.677821,-50.606218,-9.670481,-24.409263,-50.303397,25.670000,-9.712404,-112.642468,-176.428269,-41.339006,17.942115,-25.184199,23.596282,29.754840,-7.701154,-202.146622,-51.178917,-44.747420,-6.494955,-17.201449,-85.297673,28.248276,50.375769,30.546506,-39.791442,-13.124968,-1.511667,-8.649712,22.815481,10.862179,-3.110929,18.961378,16.639679,-63.650577,98.337051,-97.403333,0.691026
std,99.982420,10.958890,61.611936,5.890934,35.503216,4.070478,26.660967,3.334328,31.822952,3.607066,19.141526,2.947807,13.268399,2.494389,32.385549,7.570061,0.614251,0.445153,0.071466,0.055332,0.030505,0.033668,4.795288,2.806447,2.668909,2.181230,0.480605,0.460891,1.953647,0.224880,0.368794,0.079143,7.899881,5.282689,2.422223,0.405534,22.221493,12.880051,1.865701,0.251159,0.040411,0.083733,0.106744,0.069622,0.051956,0.101493,0.192736,0.091268,0.529776,0.123960,0.334321,0.083793,0.029286,0.070866,0.408255,0.080916,0.193204,0.051787,0.015478,0.050535,0.029171,0.071597,0.266068,0.081301,0.019247,0.048067,0.219187,0.082770,0.039953,0.052296,0.680727,0.151604,0.200407,0.060956,0.028413,0.059277,0.239754,0.113235,0.23791,0.074356,0.188821,0.266065,0.181175,0.255249,0.208028,0.255550,0.100284,0.116035,0.105506,0.124442,0.124162,0.119160,0.053831,0.017952,0.061799,0.016743,0.063808,0.016754,0.092246,0.032726,0.094948,0.028552,0.100251,0.029656,0.000473,0.004050,0.001385,0.003052,0.001526,0.003894,0.058284,222.932278,0.155306,223.404542,0.005875,1.748634,0.029246,0.001644,0.002200,0.004067,0.004081,0.004682,0.001795,0.003235,0.003208,1.112007e-16,0.955586,1.413177,1.571700,1.967275,1.869659,1.811456,2.410176,2.434134,1.937853,1.821143,2.795506,4.515835,2.885361,2.997574,2.759730,1.670822,2.199278,1.426752,1.362496,1.913731,1.461270,2.191965,5.643066,2.658162,1.530123,1.626401,1.694065,1.691714,1.619614,1.604985,1.446636,1.783498,1.776248,1.700641,1.586331,8.040997,6.568560,2.766335,3.226414,2.545963,2.221387,2.712464,2.628349,0.968649,0.778037,0.754592,0.596140,0.953130,1.895755,0.779798,1.364943,1.826351,1.200232,1.113859,0.729112,1.173283,1.040080,1.122445,1.564785,0.954909,1.114765,1.087187,0.987445,0.991220,1.521121
min,142.074600,97.256200,90.460400,61.453000,51.955800,35.915600,38.504400,29.879800,54.838000,40.398800,31.207000,25.036000,23.282000,19.288000,33.935600,28.499200,2.014400,0.116600,0.260200,0.042400,0.086400,0.095800,4.265200,7.057200,5.615800,4.501200,1.858400,0.301800,3.426400,1.812400,0.281400,0.693200,25.549200,4.517000,3.516600,2.317800,10.914800,19.889000,2.929600,1.760400,0.000000,0.000000,0.050000,0.218000,0.000000,0.000000,0.139600,0.313400,0.537000,0.357400,0.433600,0.342400,0.000000,0.000000,0.610000,0.364800,0.247600,0.188600,0.000000,0.000000,0.000000,0.000000,0.381200,0.380800,0.000000,0.000000,0.393600,0.059200,0.000400,0.012800,0.870800,0.243800,0.127200,0.154400,0.000000,0.000000,0.279400,0.483000,0.09360,0.220000,16.828200,0.045400,16.214400,0.047400,14.529600,0.046800,7.106400,0.104400,7.628400,0.096200,6.312800,0.097400,1.549800,0.099600,1.036600,0.084800,1.003000,0.087200,1.066600,0.121600,0.700200,0.094400,0.607100,0.105400,0.006480,0.277380,0.017260,0.049300,0.000000,0.167200,0.127480,0.257900,4.252686,15763.319417,-0.004114,48.163886,-0.418857,0.068571,0.051429,0.051429,0.057143,0.045714,0.061714,0.022857,0.034286,1.714286e-02,-5.020000,-1.340000,-58.850000,-2.230000,-1.650000,-24.910000,-40.380000,-4.420000,-6.290000,-19.300000,-29.680000,0.700000,-113.240000,-24.230000,-98.710000,43.880000,-58.931000,-21.579000,-39.480000,54.139000,5.525000,-29.571000,-1090.490000,-47.840000,5.690000,34.470000,153.770000,-10.330000,-40.690000,-56.000000,-16.000000,-30.910000,-55.700000,17.900000,-15.250000,-132.910000,-201.370000,-52.330000,6.900000,-32.100000,13.920000,22.690000,-14.860000,-205.129000,-53.013000,-46.614000,-8.175000,-20.691000,-90.774000,25.630000,43.835000,22.720000,-43.260000,-15.800000,-3.230000,-12.430000,19.780000,6.700000,-10.510000,16.370000,13.120000,-66.860000,95.840000,-100.600000,-4.200000
25%,218.165250,123.194600,142.177350,76.868450,80.785800,46.278500,60.594150,36.317750,78.223950,51.049950,45.964350,33.210900,31.352000,23.765200,58.308000,36.023300,2.625000,0.307850,0.329550,0.064350,0.138550,0.128400,8.237200,10.392500,9.361450,5.644600,2.504200,0.465100,4.809300,2.232650,0.864900,0.878600,33.207350,6.783650,5.231900,3.088550,33.103100,33.210750,3.950050,2.239450,0.005600,0.056800,0.143600,0.328050,0.000600,0.012800,0.330350,0.422550,0.867000,0.613350,0.775550,0.490000,0.000000,0.000000,0.891250,0.531400,0.447900,0.299200,0.000000,0.000000,0.000000,0.000000,0.582650,0.555150,0.000000,0.000000,0.499800,0.147700,0.006000,0.058050,1.372600,0.438450,0.350750,0.295550,0.000000,0.000000,0.516150,0.659450,0.21310,0.344650,16.915850,0.053200,16.280950,0.055400,16.291100,0.054400,7.195950,0.115800,7.747800,0.109000,7.392950,0.112150,1.658250,0.128150,1.164600,0.109400,1.131700,0.109550,1.298900,0.164800,0.818950,0.123100,0.787300,0.138200,0.008300,0.330130,0.024100,0.053120,0.000000,0.174165,0.133930,0.264325,5.101000,19614.828450,0.085714,57.450286,-0.373286,0.074286,0.062857,0.057143,0.068571,0.062857,0.068571,0.022857,0.034286,1.714286e-02,-2.335000,2.390000,-54.387500,1.595000,2.965000,-20.190000,-32.915000,-0.447500,0.055000,-14.330000,-24.852500,16.642500,-104.447500,-17.520000,-90.032500,47.917500,-50.103000,-18.765000,-36.572500,58.265000,10.380750,-22.645000,-1075.200000,-39.510000,9.140000,38.245000,157.705000,-7.710000,-35.640000,-51.302500,-10.290000,-24.990000,-51.180000,24.840000,-10.240000,-117.500000,-179.790000,-42.830000,16.740000,-26.390000,22.660000,28.312500,-9.730000,-202.630250,-51.719000,-45.278250,-6.820750,-17.741750,-86.538750,27.901750,49.568000,29.867500,-40.502500,-13.760000,-2.010000,-9.290000,22.227500,10.280000,-3.885000,18.347500,15.922500,-64.200000,97.787500,-97.920000,-0.200000
50%,242.314500,130.491300,157.909600,80.335700,89.785600,49.006300,68.486100,38.872000,87.607300,53.138700,52.083500,34.937100,36.058300,25.825900,66.650900,39.800600,2.862900,1.121000,0.361100,0.163000,0.158100,0.165100,10.774600,12.298800,11.384900,8.731800,2.764200,1.266700,5.308800,2.395700,1.013200,0.932300,36.446500,15.965400,5.956300,3.416400,40.215200,37.687800,4.439100,2.472000,0.021000,0.106100,0.198700,0.375000,0.019100,0.094600,0.425600,0.477900,1.079200,0.708800,0.899100,0.541500,0.016900,0.077400,1.007100,0.586200,0.507700,0.332500,0.004600,0.044100,0.008200,0.054800,0.702100,0.611600,0.005700,0.045300,0.555700,0.250200,0.015800,0.095000,1.537300,0.558600,0.419200,0.332200,0.005200,0.038600,0.649500,0.746900,0.28030,0.404900,16.936700,0.056000,16.304900,0.058300,16.315600,0.057600,7.232800,0.123200,7.784100,0.115800,7.434600,0.119700,1.698900,0.136700,1.204000,0.117300,1.174600,0.117600,1.349600,0.181500,0.874400,0.139200,0.840800,0.156000,0.008360,0.332210,0.025060,0.054770,0.000000,0.176720,0.136090,0.266360,5.101000,19643.548150,0.085714,58.323429,-0.348000,0.074286,0.062857,0.057143,0.074286,0.068571,0.068571,0.022857,0.040000,1.714286e-02,-1.860000,2.960000,-53.460000,2.590000,3.965000,-19.210000,-31.500000,1.070000,0.770000,-12.920000,-24.065000,18.940000,-102.510000,-15.300000,-88.600000,48.870000,-48.616500,-17.706500,-35.373000,59.146000,10.918000,-21.696000,-1072.070000,-37.920000,9.970000,39.735000,158.460000,-6.360000,-34.590000,-50.430000,-9.520000,-24.545000,-50.205000,25.850000,-9.620000,-112.310000,-175.910000,-41.730000,18.010000,-25.810000,23.785000,29.715000,-7.935000,-202.127000,-51.224000,-44.683000,-6.551000,-17.134000,-84.672000,28.329500,50.231000,30.570000,-39.920000,-13.435000,-1.680000,-8.500000,22.580000,11.050000,-2.950000,18.850000,16.800000,-63.850000,98.350000,-97.225000,0.300000
75%,407.397000,136.558850,257.271150,83.714250,144.512850,51.656350,111.350250,41.042000,138.222600,55.018000,80.018350,36.659650,55.945500,27.249000,113.228400,48.875750,3.880400,1.204600,0.471450,0.177450,0.178650,0.186700,15.739800,14.777300,13.943150,9.692850,3.440100,1.402650,8.614000,2.541800,1.377500,0.982050,48.860250,17.455600,10.117050,3.674600,70.521850,56.469050,7.595750,2.637900,0.061000,0.185600,0.273250,0.430650,0.058350,0.182850,0.612500,0.573400,1.729750,0.802450,1.345250,0.597250,0.039950,0.130050,1.683900,0.629650,0.817450,0.365900,0.012600,0.083050,0.031900,0.120500,1.033250,0.663950,0.016650,0.080050,0.969700,0.291700,0.031650,0.134050,2.804150,0.673600,0.673050,0.367450,0.029250,0.093150,0.877600,0.830450,0.37845,0.466250,16.956400,0.060000,16.327200,0.062400,16.337100,0.061800,7.272300,0.133000,7.826000,0.125200,7.481800,0.130700,1.732250,0.146400,1.248100,0.127450,1.218200,0.127650,1.406200,0.201850,0.942100,0.158450,0.912650,0.176200,0.008420,0.333885,0.026060,0.057005,0.000000,0.179860,0.138265,0.268780,5.281000,19661.049600,0.091429,59.239429,-0.327857,0.074286,0.062857,0.062857,0.074286,0.068571,0.068571,0.028571,0.040000,1.714286e-02,-1.220000,4.062500,-52.587500,4.315000,5.200000,-18.052500,-30.647500,2.992500,2.260000,-11.705000,-22.130000,22.310000,-101.087500,-13.410000,-87.360000,49.782500,-47.702000,-17.105750,-34.706750,60.286000,11.237000,-20.489000,-1068.710000,-37.060000,10.860000,40.350000,160.130000,-5.500000,-33.685000,-49.677500,-8.830000,-23.205000,-49.110000,26.647500,-8.665000,-108.872500,-172.102500,-39.540000,19.095000,-23.297500,24.860000,31.735000,-5.800000,-201.558000,-50.731000,-44.272000,-6.163500,-16.700250,-83.933500,28.691000,51.275000,31.730000,-39.090000,-12.505000,-1.137500,-7.820000,23.200000,11.345000,-2.090000,19.620000,17.397500,-63.055000,98.727500,-96.685000,1.700000
max,492.555000,163.811600,323.256400,98.409400,184.987800,61.647200,138.268600,49.545400,168.044600,63.949000,101.128400,43.944200,72.572600,33.284200,160.085600,59.994400,3.979600,1.503600,0.502200,0.215800,0.259000,0.235800,28.517000,20.770400,17.691400,13.680200,3.626000,1.725800,10.149400,3.085400,2.024400,1.133000,52.826200,21.846600,11.388200,4.627600,105.695200,72.675200,9.010800,2.981000,0.180000,0.424000,0.701600,0.595200,0.471000,0.430800,0.987200,0.741600,2.730000,1.038200,1.904400,0.791000,0.133400,0.261400,2.157000,0.902400,0.956600,0.536800,0.098400,0.240600,0.166000,0.299200,1.552000,0.848800,0.200000,0.254000,0.995800,0.387000,0.588000,0.269800,2.963800,1.014600,0.900400,0.470800,0.176000,0.239800,1.381600,1.016800,3.89680,0.571800,20.223200,4.754800,19.450400,4.566000,19.465400,4.570600,8.676200,2.159400,9.309800,2.304000,8.892000,2.212000,1.877600,0.303400,1.424800,0.242400,1.395000,0.230600,1.766800,0.345200,1.257000,0.265000,1.265600,0.275000,0.015040,0.338400,0.028540,0.079940,0.026960,0.194560,1.164000,3938.035720,5.773000,19720.139800,0.097143,62.804571,-0.241143,0.080000,0.068571,0.074286,0.085714,0.074286,0.068571,0.034286,0.045714,1.714286e-02,1.140000,7.320000,-49.020000,11.560000,8.200000,-13.260000,-24.790000,8.100000,5.130000,-7.780000,-9.860000,29.680000,-96.730000,-4.090000,-79.800000,53.670000,-42.223000,-13.471000,-31.379000,65.945000,14.829000,-14.671000,-1054.840000,-32.560000,14.460000,43.640000,163.940000,-0.110000,-30.650000,-46.490000,-6.680000,-17.850000,-45.830000,30.130000,-6.250000,-80.830000,-161.980000,-33.640000,27.590000,-17.670000,29.390000,36.580000,-0.720000,-199.243000,-48.819000,-41.973000,-4.732000,-14.626000,-81.201000,31.170000,54.394000,34.970000,-36.150000,-8.750000,1.140000,-5.800000,26.480000,14.480000,0.130000,21.810000,19.010000,-60.210000,103.750000,-95.520000,5.000000

In [6]:
X = vavg.drop(['DELTA30'], axis=1)
Y = vavg['DELTA30']

In [7]:
corr_matrix = df.corr()
corr_matrix.style.background_gradient(cmap='coolwarm')

C:\Users\Nick\miniconda3\envs\torch\lib\site-packages\pandas\io\formats\style.py:2780: RuntimeWarning: All-NaN slice encountered
  smin = np.nanmin(gmap) if vmin is None else vmin
C:\Users\Nick\miniconda3\envs\torch\lib\site-packages\pandas\io\formats\style.py:2781: RuntimeWarning: All-NaN slice encountered
  smax = np.nanmax(gmap) if vmax is None else vmax

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)

In [9]:
X

     pock_volume  pock_volume_st  pock_asa  pock_asa_st  pock_pol_asa  \
0       0.211233        0.360938  0.215359     0.431492      0.228855
1       0.242027        0.368478  0.229871     0.404017      0.232096
2       0.878118        0.764184  0.834672     0.663117      0.858302
3       0.825400        0.551700  0.754447     0.430480      0.717617
4       0.801595        0.799923  0.767154     0.750143      0.737899
5       0.926695        0.447910  0.857364     0.347739      0.805478
6       0.984025        0.532660  0.923895     0.451040      0.907278
7       0.777663        0.699568  0.747452     0.643326      0.732421
8       0.786768        0.510459  0.777892     0.451013      0.743964
9       0.285046        0.530851  0.292073     0.574531      0.270566
10      0.260532        0.231951  0.227570     0.196724      0.171452
11      0.423237        0.726709  0.386464     0.767835      0.365814
12      0.280605        0.318625  0.265426     0.394118      0.230164
13      0.304669        0.362678  0.286251     0.394118      0.283375
14      0.245516        0.405268  0.248051     0.434940      0.231096
15      0.287446        0.551988  0.285151     0.636209      0.248274
16      0.185953        0.433738  0.191609     0.523471      0.215005
17      0.300974        0.683034  0.296124     0.746485      0.287845
18      0.349293        0.530337  0.325018     0.552494      0.298014
19      0.249535        0.666642  0.251485     0.809327      0.234035
20      0.277069        0.495521  0.252321     0.535496      0.251454
21      0.287867        0.377238  0.278421     0.365468      0.288800
22      0.181290        0.409581  0.180889     0.535344      0.173194
23      0.269200        0.730474  0.262891     0.716222      0.258881
24      0.262460        0.323120  0.250424     0.356620      0.225125
25      0.237552        0.617477  0.252319     0.735099      0.258051
26      0.293380        0.460657  0.294804     0.524721      0.328752
27      0.325250        0.339696  0.330312     0.483462      0.302478
28      0.801686        0.534899  0.740676     0.478791      0.635710
29      0.744709        0.473675  0.703344     0.409288      0.744979
30      0.720825        0.663375  0.695883     0.616792      0.658966
31      0.819804        0.682400  0.751684     0.553636      0.704372
32      0.829307        0.615827  0.782656     0.532801      0.764811
33      0.888368        0.579247  0.849844     0.507874      0.878491
34      0.923163        0.580259  0.924989     0.541644      0.896030
35      0.800888        0.646373  0.741409     0.609854      0.678020
36      0.827811        0.638602  0.805029     0.570429      0.764359
37      0.889058        0.707759  0.824389     0.618231      0.763349
38      0.882601        0.737749  0.803260     0.681885      0.782840
39      0.707196        0.976020  0.721066     1.000000      0.779656
40      0.898273        0.535334  0.863087     0.485496      0.852795
41      0.875511        0.489947  0.834885     0.432347      0.825301
42      0.702959        0.660692  0.715736     0.655221      0.735181
43      0.902004        0.625422  0.834690     0.541795      0.764942
44      0.694741        0.583727  0.669176     0.564476      0.623683
45      0.743717        0.646806  0.693143     0.547196      0.650093
46      0.891273        0.656554  0.825460     0.583006      0.855475
47      0.877425        0.550209  0.837161     0.443414      0.890294
48      0.770502        0.668871  0.738390     0.666667      0.780871
49      0.921635        0.581014  0.896184     0.527887      0.822074
50      0.755938        0.606950  0.730344     0.579688      0.806472
51      0.727240        0.607263  0.680272     0.494361      0.632293
52      0.768713        0.571256  0.704849     0.476967      0.668026
53      0.890451        0.405485  0.853748     0.312189      0.851957
54      0.921233        0.664379  0.858612     0.587362      0.822092
55      0.778596        0.749754  0.742523     0.672311      0.711079
56      0.838210        0.701274  0.742104     0.560666      0.747501
57      0.891115        0.582240  0.835800     0.504178      0.843356
58      0.827776        0.516361  0.828065     0.528076      0.870288
59      0.610885        0.595828  0.601356     0.594809      0.564188
60      0.891556        0.519213  0.870558     0.574455      0.870681
61      0.874047        0.457459  0.838580     0.382640      0.917570
62      0.844300        0.677974  0.817302     0.685521      0.815530
63      0.822630        0.643440  0.782336     0.552299      0.756849
64      0.813046        0.568462  0.770825     0.499459      0.775737
65      0.706669        0.750596  0.649175     0.661120      0.605648
66      0.897880        0.675119  0.854817     0.632475      0.849301
67      0.851312        0.425339  0.845285     0.354748      0.891310
68      0.702934        0.669623  0.685451     0.770162      0.696058
69      0.772864        0.588758  0.710721     0.540004      0.689156
70      0.875672        0.599465  0.797431     0.507625      0.700436
71      0.766890        1.000000  0.787060     0.979208      0.772138
72      0.927002        0.546249  0.868976     0.496645      0.903952
73      0.726156        0.511207  0.684794     0.388842      0.695475
74      0.891952        0.599966  0.803292     0.501283      0.737460
75      0.716614        0.659333  0.662490     0.577069      0.677598
76      0.698542        0.493634  0.629883     0.352561      0.631525
77      0.791815        0.518245  0.705526     0.414905      0.631702
78      0.872575        0.488285  0.854987     0.438111      0.831167
79      0.926467        0.551730  0.868669     0.505011      0.878384
80      0.836322        0.612254  0.826750     0.629991      0.848712
81      0.841236        0.522275  0.811506     0.515185      0.772312
82      0.984717        0.806044  0.957169     0.817666      0.980005
83      0.841285        0.502577  0.787508     0.422417      0.805947
84      0.845485        0.650472  0.806905     0.628763      0.854167
85      0.884582        0.500768  0.873328     0.423851      0.967886
86      0.913481        0.563615  0.855575     0.486855      0.822997
87      0.841141        0.642316  0.779191     0.594825      0.771130
88      0.967817        0.758213  0.870681     0.618956      0.804405
89      0.658261        0.647857  0.615486     0.686896      0.630890
90      0.939946        0.683205  0.880390     0.577654      0.908470
91      0.849709        0.543854  0.820602     0.444811      0.832350
92      0.938317        0.626260  0.845561     0.500720      0.853123
93      0.865634        0.542168  0.837342     0.512144      0.940571
94      0.860147        0.534598  0.812150     0.417865      0.829603
95      0.715047        0.597860  0.718723     0.586561      0.697434
96      0.903869        0.458169  0.873272     0.396462      0.908593
97      0.781179        0.571365  0.763595     0.601276      0.797471
98      0.949060        0.389258  0.904223     0.207975      0.978937
99      0.260902        0.401750  0.250435     0.445168      0.274384
100     0.263046        0.514260  0.283119     0.566787      0.304877
101     0.274165        0.355163  0.300496     0.481670      0.354670
102     0.235622        0.497952  0.216571     0.538467      0.180669
103     0.362032        0.669743  0.386679     0.830341      0.377517
104     0.331091        0.324593  0.326081     0.419857      0.345995
105     0.207659        0.449277  0.182694     0.426172      0.185955
106     0.247708        0.402777  0.252301     0.521073      0.211465
107     0.192238        0.688010  0.200308     0.784600      0.198179
108     0.220123        0.516262  0.242095     0.612690      0.228348
109     0.284667        0.198394  0.281215     0.178951      0.285357
110     0.249425        0.383088  0.249808     0.452122      0.253171
111     0.335119        0.541050  0.356040     0.692935      0.369218
112     0.290388        0.438209  0.280686     0.485480      0.211951
113     0.281439        0.602154  0.274158     0.680440      0.220120
114     0.221162        0.329665  0.210462     0.390926      0.197564
115     0.153678        0.018745  0.147880     0.052164      0.105502
116     0.244825        0.357864  0.275576     0.449963      0.331631
117     0.204062        0.019857  0.200293     0.043370      0.196667
118     0.239700        0.317300  0.242929     0.338020      0.242071
119     0.270835        0.216367  0.295706     0.315052      0.269289
120     0.123641        0.040429  0.117946     0.000000      0.071423
121     0.263712        0.646199  0.267228     0.721997      0.259477
122     0.333400        0.412694  0.334497     0.459000      0.286309
123     0.305886        0.478329  0.292728     0.559481      0.279627
124     0.229573        0.338779  0.236093     0.455326      0.239357
125     0.232906        0.646911  0.237836     0.711855      0.215037
126     0.135335        0.428744  0.143291     0.510899      0.122255
127     0.230332        0.547889  0.223337     0.572166      0.231965
128     0.162961        0.176470  0.144620     0.123145      0.134686
129     0.152253        0.389883  0.161967     0.450796      0.185498
130     0.220122        0.320494  0.216679     0.349715      0.169944
131     0.110634        0.753432  0.129633     0.795797      0.107388
132     0.189199        0.269517  0.198024     0.307178      0.167236
133     0.269038        0.531467  0.266241     0.532974      0.268731
134     0.281655        0.306199  0.259300     0.317704      0.233924
135     0.124421        0.530872  0.132228     0.575884      0.112359
136     0.167285        0.311389  0.182647     0.357134      0.168624
137     0.217504        0.463566  0.226414     0.544517      0.245431
138     0.165792        0.064614  0.153568     0.009519      0.103480
139     0.279967        0.538715  0.264095     0.600551      0.240447
140     0.328493        0.549686  0.334911     0.676982      0.331913
141     0.253484        0.304029  0.248653     0.397468      0.226693
142     0.162787        0.211646  0.151813     0.215806      0.180651
143     0.197932        0.362859  0.199536     0.427341      0.158139
144     0.232347        0.174715  0.219145     0.184693      0.220330
145     0.249004        0.443008  0.243982     0.498025      0.209647
146     0.277303        0.403138  0.269783     0.439783      0.246115
147     0.199587        0.574472  0.214151     0.643591      0.206967
148     0.255674        0.567488  0.258356     0.655177      0.264388
149     0.121315        0.405993  0.140050     0.553523      0.092251
150     0.200109        0.370077  0.212816     0.442592      0.168251
151     0.231487        0.323268  0.219384     0.395802      0.221296
152     0.200358        0.396767  0.198130     0.431427      0.161498
153     0.211312        0.432151  0.196047     0.438284      0.154500
154     0.240760        0.276395  0.241996     0.331391      0.254539
155     0.264605        0.394516  0.242520     0.428126      0.210503
156     0.231358        0.393450  0.268506     0.484636      0.264631
157     0.245496        0.361735  0.284263     0.520175      0.272685
158     0.145120        0.192504  0.141237     0.229790      0.109277
159     0.196865        0.262951  0.199393     0.328814      0.174809
160     0.274393        0.427908  0.260256     0.444567      0.254976
161     0.226742        0.495605  0.222823     0.592839      0.223292
162     0.283273        0.420837  0.277317     0.446981      0.274121
163     0.295700        0.341754  0.321836     0.488305      0.369250
164     0.279763        0.455275  0.293610     0.571939      0.279766
165     0.178603        0.275473  0.188477     0.319566      0.179406
166     0.243401        0.215321  0.236107     0.286770      0.228534
167     0.237609        0.432656  0.271554     0.583233      0.317208
168     0.308459        0.286663  0.303077     0.306826      0.222228
169     0.310265        0.512319  0.317077     0.584175      0.303205
170     0.196459        0.341808  0.202740     0.405467      0.235901
171     0.362651        0.584896  0.349100     0.645247      0.356035
172     0.212313        0.476370  0.231076     0.591557      0.264896
173     0.175252        0.234626  0.182449     0.189007      0.166840
174     0.116799        0.414650  0.107578     0.414764      0.086224
175     0.209153        0.448321  0.224411     0.512691      0.230301
176     0.295082        0.472172  0.309665     0.510991      0.362307
177     0.189939        0.551670  0.195247     0.639191      0.161969
178     0.325125        0.603828  0.321374     0.771834      0.346213
179     0.197175        0.435667  0.176366     0.477238      0.184378
180     0.345705        0.510630  0.350370     0.627550      0.399943
181     0.313059        0.543439  0.311967     0.622409      0.319293
182     0.561283        0.339513  0.527963     0.318732      0.488027
183     0.251151        0.329864  0.266728     0.318251      0.286405
184     0.176673        0.406071  0.189937     0.422173      0.221880
185     0.157228        0.514074  0.163805     0.590512      0.158965
186     0.245722        0.388134  0.260876     0.483532      0.261197
187     0.282910        0.608158  0.290073     0.727338      0.294240
188     0.269830        0.479075  0.256880     0.503220      0.255600
189     0.260423        0.620217  0.262462     0.695084      0.242200
190     0.218922        0.201757  0.224035     0.313515      0.224483
191     0.241465        0.451960  0.248966     0.525289      0.261833
192     0.229265        0.369962  0.219716     0.374474      0.232532
193     0.191350        0.339435  0.203418     0.377163      0.195338
194     0.181404        0.426328  0.168863     0.435042      0.163597
195     0.213438        0.412742  0.223145     0.515148      0.244782
196     0.052973        0.321041  0.056702     0.443036      0.067836
197     0.250941        0.478552  0.239543     0.506716      0.235809
198     0.212101        0.213500  0.239863     0.297756      0.266162
199     0.196920        0.493117  0.191792     0.539820      0.189756
200     0.305115        0.393495  0.301456     0.412881      0.320057
201     0.311949        0.560943  0.316276     0.669313      0.301535
202     0.215477        0.379059  0.215042     0.445249      0.212678
203     0.354027        0.526283  0.354766     0.615964      0.335176
204     0.203937        0.267026  0.175381     0.277035      0.172049
205     0.394076        0.401359  0.394196     0.442170      0.392875
206     0.256071        0.443648  0.266326     0.591253      0.288893
207     0.232977        0.319740  0.252085     0.414207      0.259249
208     0.284957        0.673265  0.295962     0.820047      0.310116
209     0.326710        0.477407  0.347916     0.442359      0.314282
210     0.243586        0.449505  0.233439     0.404379      0.207866
211     0.155382        0.545567  0.144123     0.570396      0.133957
212     0.102187        0.278898  0.125374     0.345158      0.109835
213     0.284423        0.508990  0.265186     0.517610      0.257370
214     0.104196        0.573805  0.122410     0.686225      0.147353
215     0.224594        0.225343  0.227321     0.273024      0.166306
216     0.171207        0.574421  0.181074     0.667089      0.199705
217     0.088396        0.341706  0.109475     0.430854      0.093510
218     0.262481        0.409073  0.268201     0.456733      0.259550
219     0.291917        0.623195  0.307633     0.684758      0.326923
220     0.377974        0.547835  0.392478     0.725671      0.372371
221     0.184261        0.437545  0.183766     0.480252      0.156654
222     0.400638        0.751777  0.377287     0.735450      0.313977
223     0.149729        0.456943  0.156027     0.583093      0.135417
224     0.233759        0.439447  0.229626     0.424040      0.228228
225     0.215904        0.481740  0.220152     0.548982      0.222378
226     0.343620        0.551979  0.339096     0.656855      0.325487
227     0.206781        0.557046  0.227400     0.724957      0.254909
228     0.219153        0.529772  0.243594     0.709658      0.259959
229     0.253207        0.494469  0.273147     0.745911      0.319182
230     0.186695        0.135667  0.205878     0.291587      0.239112
231     0.174313        0.000000  0.165180     0.031015      0.118274
232     0.211366        0.147841  0.191565     0.203678      0.195479
233     0.091744        0.582123  0.113289     0.712369      0.115106
234     0.204355        0.529075  0.224371     0.604658      0.260382
235     0.123282        0.415047  0.163976     0.589354      0.180205
236     0.198508        0.318547  0.197649     0.447127      0.194920
237     0.298616        0.318688  0.310741     0.354391      0.248546
238     0.338245        0.399240  0.333062     0.409033      0.351350
239     0.131754        0.000517  0.143185     0.063080      0.141124
240     0.306059        0.454355  0.298324     0.543624      0.235330
241     0.253232        0.508052  0.252802     0.563302      0.269938
242     0.220221        0.228793  0.225829     0.314652      0.212298
243     0.188098        0.277645  0.203130     0.260015      0.257606
244     0.184290        0.384095  0.171825     0.340921      0.148694
245     0.248251        0.392572  0.234881     0.430886      0.184368
246     0.096513        0.578988  0.110766     0.669681      0.140088
247     0.179428        0.038629  0.184178     0.081561      0.201067
248     0.124351        0.207496  0.128193     0.322223      0.137651
249     0.156020        0.329990  0.159772     0.359808      0.163228
250     0.306308        0.521986  0.289398     0.596167      0.303399
251     0.281980        0.632258  0.256698     0.617295      0.267143
252     0.270454        0.461246  0.275363     0.528536      0.255716
253     0.130792        0.412568  0.150903     0.488175      0.158165
254     0.182313        0.331032  0.191575     0.446358      0.217274
255     0.265759        0.574947  0.255114     0.601953      0.247381
256     0.341005        0.563678  0.337562     0.636247      0.318989
257     0.305878        0.603623  0.321910     0.692584      0.331633
258     0.129010        0.292274  0.131302     0.295765      0.115832
259     0.266285        0.458391  0.278110     0.578612      0.263328
260     0.210968        0.451804  0.202849     0.519807      0.190554
261     0.000000        0.166298  0.000000     0.244932      0.000000
262     0.295025        0.404241  0.301034     0.449070      0.268051
263     0.082068        0.280831  0.093600     0.394914      0.073259
264     0.308311        0.629328  0.308792     0.696551      0.283004
265     0.118082        0.399066  0.119694     0.427423      0.150707
266     0.304501        0.508274  0.294692     0.594176      0.279443
267     0.197383        0.586594  0.204357     0.691366      0.209087
268     0.297622        0.500882  0.277086     0.524017      0.229608
269     0.271778        0.461630  0.275567     0.480274      0.286257
270     0.169063        0.577507  0.181606     0.719897      0.206263
271     0.254610        0.344288  0.245587     0.367574      0.255593
272     0.068993        0.111315  0.073052     0.194781      0.071856
273     0.286968        0.323087  0.288427     0.411301      0.260167
274     0.242331        0.548175  0.233006     0.596557      0.233069
275     0.279676        0.437711  0.292157     0.544485      0.289858
276     0.164894        0.372493  0.163834     0.400672      0.132511
277     0.172776        0.422839  0.171420     0.486471      0.174653
278     0.401552        0.647352  0.387270     0.654712      0.391017
279     0.404861        0.448577  0.386779     0.426389      0.368732
280     0.596231        0.635365  0.543036     0.516241      0.540721
281     0.580137        0.731180  0.586946     0.717813      0.572258
282     0.629299        0.495037  0.610780     0.405976      0.616008
283     0.635572        0.667131  0.649020     0.719128      0.657382

In [10]:
seed = 7
model = xgb.LGBMRegressor(verbosity=0)
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=7)
scores = cross_val_score(model, X, Y, scoring='neg_mean_absolute_error', cv=cv, n_jobs=1)
scores = absolute(scores)
print('Mean MAE: %.3f (%.3f)' % (scores.mean(), scores.std()))

[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001278 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001226 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001214 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [11]:
seed = 7
test_size = 0.2

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=seed)
model = xgb.LGBMRegressor(verbosity=0)
eval_set = [(X_train, y_train), (X_test, y_test)]
model.fit(X_train, y_train, eval_metric=["mae", "rmse"], eval_set=eval_set, verbose=True, early_stopping_rounds=10)
y_pred = model.predict(X_test)
predictions = [value for value in y_pred]
predictions
results = model.evals_result_

[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001129 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[1]	training's l1: 1.09351	training's rmse: 1.39034	training's l2: 1.93304	valid_1's l1: 1.24148	valid_1's rmse: 1.59242	valid_1's l2: 2.53581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[2]	training's l1: 1.0251	training's rmse: 1.31097	training's l2: 1.71864	valid_1's l1: 1.18799	valid_1's rmse: 1.52648	valid_1's l2: 2.33015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[3]	training's l1: 0.966357	training's rmse: 1.24772	training's l2: 1.5568	valid_1's l1: 1.13909	valid_1's rmse: 1.46871	valid_1's l2: 2.15711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[4]	training's l1: 0.908298	training's rmse: 1.18524	training's l2: 1.4048	valid_1's l1: 1.10104	valid_1's rmse: 1.42126	valid_1's l2: 2.01997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[5]	training's l1: 0.863075	training's rmse: 1.13537	training's l2: 1.28905	valid_1's l1: 1.06171	valid_1's rmse: 1.37665	valid_1's l2: 1.89516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[6]	training's l1: 0.822834	training's rmse: 1.08884	training's l2: 1.18557	valid_1's l1: 1.03019	valid_1's rmse: 1.34321	valid_1's l2: 1.80421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[7]	training's l1: 0.776857	training's rmse: 1.0403	training's l2: 1.08222	valid_1's l1: 1.00749	valid_1's rmse: 1.31953	valid_1's l2: 1.74115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[8]	training's l1: 0.743103	training's rmse: 0.999986	training's l2: 0.999971	valid_1's l1: 0.980084	valid_1's rmse: 1.29368	valid_1's l2: 1.6736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[9]	training's l1: 0.706542	training's rmse: 0.962415	training's l2: 0.926242	valid_1's l1: 0.96536	valid_1's rmse: 1.28146	valid_1's l2: 1.64214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[10]	training's l1: 0.674333	training's rmse: 0.929421	training's l2: 0.863824	valid_1's l1: 0.946707	valid_1's rmse: 1.26392	valid_1's l2: 1.59749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[11]	training's l1: 0.650483	training's rmse: 0.90165	training's l2: 0.812972	valid_1's l1: 0.942879	valid_1's rmse: 1.2608	valid_1's l2: 1.58963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[12]	training's l1: 0.625817	training's rmse: 0.872515	training's l2: 0.761283	valid_1's l1: 0.933688	valid_1's rmse: 1.24778	valid_1's l2: 1.55696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[13]	training's l1: 0.605288	training's rmse: 0.848013	training's l2: 0.719126	valid_1's l1: 0.926171	valid_1's rmse: 1.24398	valid_1's l2: 1.5475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[14]	training's l1: 0.583592	training's rmse: 0.824061	training's l2: 0.679077	valid_1's l1: 0.91225	valid_1's rmse: 1.23297	valid_1's l2: 1.52022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[15]	training's l1: 0.568532	training's rmse: 0.804722	training's l2: 0.647577	valid_1's l1: 0.907145	valid_1's rmse: 1.22793	valid_1's l2: 1.50782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[16]	training's l1: 0.546343	training's rmse: 0.777858	training's l2: 0.605063	valid_1's l1: 0.907083	valid_1's rmse: 1.22461	valid_1's l2: 1.49966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[17]	training's l1: 0.529688	training's rmse: 0.757492	training's l2: 0.573795	valid_1's l1: 0.907667	valid_1's rmse: 1.21677	valid_1's l2: 1.48054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[18]	training's l1: 0.514932	training's rmse: 0.737215	training's l2: 0.543486	valid_1's l1: 0.909341	valid_1's rmse: 1.21696	valid_1's l2: 1.48099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[19]	training's l1: 0.502219	training's rmse: 0.720264	training's l2: 0.518781	valid_1's l1: 0.902249	valid_1's rmse: 1.20865	valid_1's l2: 1.46085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[20]	training's l1: 0.485731	training's rmse: 0.69922	training's l2: 0.488909	valid_1's l1: 0.90369	valid_1's rmse: 1.21327	valid_1's l2: 1.47202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	training's l1: 0.470428	training's rmse: 0.679357	training's l2: 0.461526	valid_1's l1: 0.894406	valid_1's rmse: 1.20168	valid_1's l2: 1.44403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	training's l1: 0.457716	training's rmse: 0.665576	training's l2: 0.442992	valid_1's l1: 0.890113	valid_1's rmse: 1.19574	valid_1's l2: 1.4298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	training's l1: 0.442873	training's rmse: 0.648745	training's l2: 0.42087	valid_1's l1: 0.890281	valid_1's rmse: 1.20125	valid_1's l2: 1.443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	training's l1: 0.429164	training's rmse: 0.634874	training's l2: 0.403064	valid_1's l1: 0.892201	valid_1's rmse: 1.20404	valid_1's l2: 1.4497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	training's l1: 0.416919	training's rmse: 0.621047	training's l2: 0.385699	valid_1's l1: 0.888646	valid_1's rmse: 1.19905	valid_1's l2: 1.43771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	training's l1: 0.407961	training's rmse: 0.609444	training's l2: 0.371422	valid_1's l1: 0.888273	valid_1's rmse: 1.19632	valid_1's l2: 1.43119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	training's l1: 0.396739	training's rmse: 0.596748	training's l2: 0.356108	valid_1's l1: 0.884811	valid_1's rmse: 1.1967	valid_1's l2: 1.43208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	training's l1: 0.389799	training's rmse: 0.58505	training's l2: 0.342283	valid_1's l1: 0.883418	valid_1's rmse: 1.19337	valid_1's l2: 1.42414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	training's l1: 0.38076	training's rmse: 0.574357	training's l2: 0.329886	valid_1's l1: 0.8836	valid_1's rmse: 1.1926	valid_1's l2: 1.4223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	training's l1: 0.373271	training's rmse: 0.563446	training's l2: 0.317471	valid_1's l1: 0.878922	valid_1's rmse: 1.18907	valid_1's l2: 1.41388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	training's l1: 0.362804	training's rmse: 0.552154	training's l2: 0.304875	valid_1's l1: 0.881218	valid_1's rmse: 1.19198	valid_1's l2: 1.42082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	training's l1: 0.352176	training's rmse: 0.540453	training's l2: 0.29209	valid_1's l1: 0.879444	valid_1's rmse: 1.19004	valid_1's l2: 1.41618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	training's l1: 0.342729	training's rmse: 0.528589	training's l2: 0.279406	valid_1's l1: 0.88661	valid_1's rmse: 1.19877	valid_1's l2: 1.43706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	training's l1: 0.336614	training's rmse: 0.519147	training's l2: 0.269513	valid_1's l1: 0.889718	valid_1's rmse: 1.2034	valid_1's l2: 1.44817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	training's l1: 0.328461	training's rmse: 0.507753	training's l2: 0.257813	valid_1's l1: 0.886605	valid_1's rmse: 1.19892	valid_1's l2: 1.4374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	training's l1: 0.320781	training's rmse: 0.497578	training's l2: 0.247584	valid_1's l1: 0.890966	valid_1's rmse: 1.20436	valid_1's l2: 1.45048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	training's l1: 0.313749	training's rmse: 0.489095	training's l2: 0.239214	valid_1's l1: 0.890974	valid_1's rmse: 1.20612	valid_1's l2: 1.45472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	training's l1: 0.306023	training's rmse: 0.479911	training's l2: 0.230314	valid_1's l1: 0.886103	valid_1's rmse: 1.20094	valid_1's l2: 1.44225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	training's l1: 0.298907	training's rmse: 0.469575	training's l2: 0.220501	valid_1's l1: 0.88642	valid_1's rmse: 1.20365	valid_1's l2: 1.44877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	training's l1: 0.29435	training's rmse: 0.463396	training's l2: 0.214736	valid_1's l1: 0.885143	valid_1's rmse: 1.2026	valid_1's l2: 1.44626

C:\Users\Nick\miniconda3\envs\torch\lib\site-packages\lightgbm\sklearn.py:726: UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
  _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "
C:\Users\Nick\miniconda3\envs\torch\lib\site-packages\lightgbm\sklearn.py:736: UserWarning: 'verbose' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose' argument is deprecated and will be removed in a future release of LightGBM. "

In [12]:
epoch = len(results['validation_0']['mae'])
x_axis = range(0, epoch)
# plot log loss
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['mae'], label='Train')
ax.plot(x_axis, results['validation_1']['mae'], label='Test')
ax.legend()
pyplot.ylabel('Mean Absolute Error')
pyplot.title('XGBoost MAE')
#pyplot.savefig('XGBoost_MAE_raw.png')
pyplot.show()
# plot classification error
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['trainings l1']['rmse'], label='Train')
ax.plot(x_axis, results['validation_1']['rmse'], label='Test')
ax.legend()
pyplot.ylabel('Root Mean Square Error')
pyplot.title('XGBoost RMSE')
#pyplot.savefig('XGBoost_RMSE_raw.png')
pyplot.show()

KeyError: 'validation_0'

In [ ]:
import xgboost as xgb
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import fbeta_score, make_scorer
from xgboost.sklearn import LGBMRegressor

parameters = {'objective':['reg:squarederror'],
              'booster':['gbtree','gblinear'],
              'learning_rate': [0.001,0.004,0.008,0.01,0.02,0.03,0.04,0.05,0.06,0.07,
                                0.08,0.09,0.1,0.2,0.4,0.6,0.8,1],
              'max_depth': range(1,100,10),
              'min_child_weight': range(5,100,5),
              'colsample_bytree': [0.1,0.2,0.4,0.8,1],
              'n_estimators': range(10,1000,10),
              "reg_alpha"   : [0.1,0.2,0.4,0.6,0.8,1],
              "reg_lambda"  : range(1,10,1),
              "gamma"       : range(1,10,1)}

xgb_model = LGBMRegressor(random_state=7)

grid_obj_xgb = RandomizedSearchCV(xgb_model,parameters, cv=5,n_iter=15,scoring='neg_mean_absolute_error',verbose=5,n_jobs=12)
grid_obj_xgb.fit(X_train, y_train, verbose=1)

y_pred_train = grid_obj_xgb.predict(X_train)
y_pred_test = grid_obj_xgb.predict(X_test)

err_xgb_train=mean_absolute_error(y_train, y_pred_train, multioutput='raw_values')

In [ ]:
print('\n All results:')
print(grid_obj_xgb.cv_results_)
print('\n Best estimator:')
print(grid_obj_xgb.best_estimator_)
print('\n Best hyperparameters:')
print(grid_obj_xgb.best_params_)
results = pd.DataFrame(grid_obj_xgb.cv_results_)#

In [ ]:
Best_estimator = LGBMRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=6, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.04, max_delta_step=0, max_depth=51,
             min_child_weight=15, monotone_constraints='()',
             n_estimators=680, n_jobs=0, num_parallel_tree=1, random_state=7,
             reg_alpha=0.8, reg_lambda=9, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [ ]:
seed = 7
test_size = 0.2

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=seed)
eval_set = [(X_train, y_train), (X_test, y_test)]
Best_estimator.fit(X_train, y_train, eval_metric=["mae", "rmse"], eval_set=eval_set, verbose=True, early_stopping_rounds=10)
y_pred = Best_estimator.predict(X_test)
predictions = [value for value in y_pred]
predictions
results = Best_estimator.evals_result()
epoch = len(results['validation_0']['mae'])
x_axis = range(0, epoch)
# plot log loss
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['mae'], label='Train')
ax.plot(x_axis, results['validation_1']['mae'], label='Test')
ax.legend()
pyplot.ylabel('Mean Absolute Error')
pyplot.title('XGBoost MAE')
pyplot.savefig('XGBoost_MAE_tuned.png')
pyplot.show()
# plot classification error
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['rmse'], label='Train')
ax.plot(x_axis, results['validation_1']['rmse'], label='Test')
ax.legend()
pyplot.ylabel('Root Mean Square Error')
pyplot.title('XGBoost RMSE')
pyplot.savefig('XGBoost_RMSE_tuned.png')
pyplot.show()

In [ ]:
n_fold = [2, 3, 4, 5, 6, 7, 8, 9, 10]
for fold in n_fold:
    scores = []
    cv = KFold(n_splits=fold, shuffle=True)
    fig = plt.figure()
    i = 1
    for train, test in cv.split(X, Y):
        prediction = Best_estimator.fit(X.iloc[train],
                     Y.iloc[train]).predict(X.iloc[test])
        true = Y.iloc[test]
        score = mean_absolute_error(true, prediction)
        scores.append(score)
        plt.scatter(prediction, true, lw=2, alpha=0.3,
                    label='Fold %d (MAE = %0.2f)' % (i,score))
        i = i+1
    plt.plot([min(Y),max(Y)], [min(Y),max(Y)],
             linestyle='--', lw=2, color='black')
    plt.xlabel('Predicted Value')
    plt.ylabel('Actual Value')
    plt.title('K-Fold Validation')
    plt.legend(prop={"size":10}, loc='center left', bbox_to_anchor=(1, 0.5))
    plt.show()
    print("Average of CV:", mean(scores))
    print("All Scores of CV", scores)

In [ ]:
import eli5
from eli5.sklearn import PermutationImportance

perm = PermutationImportance(Best_estimator, random_state=1).fit(X_test, y_test)
eli5.show_weights(perm, feature_names = X_test.columns.tolist())

In [ ]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer()
booster = Best_estimator.get_booster()
original_feature_names = booster.feature_names
print(booster.get_dump()[0])
booster.feature_names = original_feature_names

In [ ]:
from eli5 import show_weights
show_weights(Best_estimator, importance_type="cover") #“cover” - the average coverage of the feature.

In [ ]:
# this might be the best one
show_weights(Best_estimator, importance_type="weight")  #"weight" - how often a feature has been used in making splits

In [ ]:
show_weights(Best_estimator, importance_type="gain") #"gain" - that is the average gain of the feature when it is used in trees.

In [ ]:
from sklearn import metrics
## Kpi
print("R2 (explained variance):", round(metrics.r2_score(y_test, predictions), 2))
print("Mean Absolute Perc Error (Σ(|y-pred|/y)/n):", round(np.mean(np.abs((y_test-predictions)/predictions)), 2))
print("Mean Absolute Error (Σ|y-pred|/n):", "{:,.2f}".format(metrics.mean_absolute_error(y_test, predictions)))
print("Root Mean Squared Error (sqrt(Σ(y-pred)^2/n)):", "{:,.2f}".format(np.sqrt(metrics.mean_squared_error(y_test, predictions))))
## residuals
residuals = []
for i, c in zip(y_test, y_pred):
    residuals.append(i - c)

In [ ]:
######## COMPARING DATASET ORIGIN #################

In [ ]:
MDPocket = X.iloc[:, :80]
MD = X.iloc[:, 80:126]
Seq = X.iloc[:, 126:]
Seq_MD = X.iloc[:, 80:]
MD_MDpocket = X.iloc[:, :126]
Seq_MDpocket = pd.concat([MDPocket, Seq], axis =1)
datasets = [MDPocket, MD, Seq, Seq_MD, MD_MDpocket, Seq_MDpocket]
for dataset in datasets:
    X_train, X_test, y_train, y_test = train_test_split(dataset, Y, test_size=0.2, random_state=7)
    xgb_model = LGBMRegressor(random_state=7)

    grid_obj_xgb = RandomizedSearchCV(xgb_model,parameters, cv=5,n_iter=15,scoring='neg_mean_absolute_error',verbose=5,n_jobs=12)
    grid_obj_xgb.fit(X_train, y_train,verbose = 1)

    y_pred_train = grid_obj_xgb.predict(X_train)
    y_pred_test = grid_obj_xgb.predict(X_test)

    err_xgb_train=mean_absolute_error(y_train, y_pred_train, multioutput='raw_values')


    print('\n All results:')
    print(grid_obj_xgb.cv_results_)
    print('\n Best estimator:')
    print(grid_obj_xgb.best_estimator_)
    print('\n Best hyperparameters:')
    print(grid_obj_xgb.best_params_)
    results = pd.DataFrame(grid_obj_xgb.cv_results_)#

In [ ]:
# MDPocket
BestMDPocket = LGBMRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.4, gamma=7, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.2, max_delta_step=0, max_depth=71,
             min_child_weight=25, monotone_constraints='()',
             n_estimators=530, n_jobs=0, num_parallel_tree=1, random_state=7,
             reg_alpha=1, reg_lambda=8, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)
X_train, X_test, y_train, y_test = train_test_split(MDPocket, Y, test_size=0.2, random_state=seed)
eval_set = [(X_train, y_train), (X_test, y_test)]
BestMDPocket.fit(X_train, y_train, eval_metric=["mae", "rmse"], eval_set=eval_set, verbose=True, early_stopping_rounds=10)
y_pred = BestMDPocket.predict(X_test)
predictions = [value for value in y_pred]
results = Best_estimator.evals_result()
epoch = len(results['validation_0']['mae'])
x_axis = range(0, epoch)
# plot log loss
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['mae'], label='Train')
ax.plot(x_axis, results['validation_1']['mae'], label='Test')
ax.legend()
pyplot.ylabel('Mean Absolute Error')
pyplot.title('XGBoost MAE')
pyplot.savefig('XGBoost_MAE_tuned.png')
pyplot.show()
# plot classification error
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['rmse'], label='Train')
ax.plot(x_axis, results['validation_1']['rmse'], label='Test')
ax.legend()
pyplot.ylabel('Root Mean Square Error')
pyplot.title('XGBoost RMSE')
pyplot.savefig('XGBoost_RMSE_tuned.png')
pyplot.show()

In [ ]:
perm = PermutationImportance(BestMDPocket, random_state=1).fit(X_test, y_test)
eli5.show_weights(perm, feature_names = X_test.columns.tolist())

In [ ]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer()
booster = BestMDPocket.get_booster()
original_feature_names = booster.feature_names
print(booster.get_dump()[0])
booster.feature_names = original_feature_names

In [ ]:
from eli5 import show_weights
show_weights(BestMDPocket, importance_type="cover") #“cover” - the average coverage of the feature.

In [ ]:
# this might be the best one
show_weights(BestMDPocket, importance_type="weight")  #"weight" - how often a feature has been used in making splits

In [ ]:
show_weights(BestMDPocket, importance_type="gain")

In [ ]:
from sklearn import metrics
## Kpi
print("R2 (explained variance):", round(metrics.r2_score(y_test, predictions), 2))
print("Mean Absolute Perc Error (Σ(|y-pred|/y)/n):", round(np.mean(np.abs((y_test-predictions)/predictions)), 2))
print("Mean Absolute Error (Σ|y-pred|/n):", "{:,.2f}".format(metrics.mean_absolute_error(y_test, predictions)))
print("Root Mean Squared Error (sqrt(Σ(y-pred)^2/n)):", "{:,.2f}".format(np.sqrt(metrics.mean_squared_error(y_test, predictions))))
## residuals
residuals = []
for i, c in zip(y_test, y_pred):
    residuals.append(i - c)

In [ ]:
BestMD = LGBMRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.8, gamma=8, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=71,
             min_child_weight=35, monotone_constraints='()',
             n_estimators=950, n_jobs=0, num_parallel_tree=1, random_state=7,
             reg_alpha=0.4, reg_lambda=6, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)
X_train, X_test, y_train, y_test = train_test_split(MD, Y, test_size=0.2, random_state=seed)
eval_set = [(X_train, y_train), (X_test, y_test)]
BestMD.fit(X_train, y_train, eval_metric=["mae", "rmse"], eval_set=eval_set, verbose=True, early_stopping_rounds=10)
y_pred = BestMD.predict(X_test)
predictions = [value for value in y_pred]
results = BestMD.evals_result()
epoch = len(results['validation_0']['mae'])
x_axis = range(0, epoch)
# plot log loss
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['mae'], label='Train')
ax.plot(x_axis, results['validation_1']['mae'], label='Test')
ax.legend()
pyplot.ylabel('Mean Absolute Error')
pyplot.title('XGBoost MAE')
pyplot.savefig('XGBoost_MAE_tuned.png')
pyplot.show()
# plot classification error
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['rmse'], label='Train')
ax.plot(x_axis, results['validation_1']['rmse'], label='Test')
ax.legend()
pyplot.ylabel('Root Mean Square Error')
pyplot.title('XGBoost RMSE')
pyplot.savefig('XGBoost_RMSE_tuned.png')
pyplot.show()

perm = PermutationImportance(BestMD, random_state=1).fit(X_test, y_test)
eli5.show_weights(perm, feature_names = X_test.columns.tolist())


from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer()
booster = BestMD.get_booster()
original_feature_names = booster.feature_names
print(booster.get_dump()[0])
booster.feature_names = original_feature_names

In [ ]:
from eli5 import show_weights
show_weights(BestMD, importance_type="cover") #“cover” - the average coverage of the feature.

In [ ]:
# this might be the best one
show_weights(BestMD, importance_type="weight")  #"weight" - how often a feature has been used in making splits

In [ ]:
show_weights(BestMD, importance_type="gain")

In [ ]:
from sklearn import metrics
## Kpi
print("R2 (explained variance):", round(metrics.r2_score(y_test, predictions), 2))
print("Mean Absolute Perc Error (Σ(|y-pred|/y)/n):", round(np.mean(np.abs((y_test-predictions)/predictions)), 2))
print("Mean Absolute Error (Σ|y-pred|/n):", "{:,.2f}".format(metrics.mean_absolute_error(y_test, predictions)))
print("Root Mean Squared Error (sqrt(Σ(y-pred)^2/n)):", "{:,.2f}".format(np.sqrt(metrics.mean_squared_error(y_test, predictions))))
## residuals
residuals = []
for i, c in zip(y_test, y_pred):
    residuals.append(i - c)

In [ ]:
BestSeq = LGBMRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=4, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.004, max_delta_step=0, max_depth=21,
             min_child_weight=25, monotone_constraints='()',
             n_estimators=400, n_jobs=0, num_parallel_tree=1, random_state=7,
             reg_alpha=0.1, reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)
X_train, X_test, y_train, y_test = train_test_split(Seq, Y, test_size=0.2, random_state=seed)
eval_set = [(X_train, y_train), (X_test, y_test)]
BestSeq.fit(X_train, y_train, eval_metric=["mae", "rmse"], eval_set=eval_set, verbose=True, early_stopping_rounds=10)
y_pred = BestSeq.predict(X_test)
predictions = [value for value in y_pred]
results = BestSeq.evals_result()
epoch = len(results['validation_0']['mae'])
x_axis = range(0, epoch)
# plot log loss
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['mae'], label='Train')
ax.plot(x_axis, results['validation_1']['mae'], label='Test')
ax.legend()
pyplot.ylabel('Mean Absolute Error')
pyplot.title('XGBoost MAE')
pyplot.savefig('XGBoost_MAE_tuned.png')
pyplot.show()
# plot classification error
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['rmse'], label='Train')
ax.plot(x_axis, results['validation_1']['rmse'], label='Test')
ax.legend()
pyplot.ylabel('Root Mean Square Error')
pyplot.title('XGBoost RMSE')
pyplot.savefig('XGBoost_RMSE_tuned.png')
pyplot.show()

perm = PermutationImportance(BestSeq, random_state=1).fit(X_test, y_test)
eli5.show_weights(perm, feature_names = X_test.columns.tolist())


from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer()
booster = BestSeq.get_booster()
original_feature_names = booster.feature_names
print(booster.get_dump()[0])
booster.feature_names = original_feature_names

In [ ]:
from eli5 import show_weights
show_weights(BestSeq, importance_type="cover") #“cover” - the average coverage of the feature.

In [ ]:
# this might be the best one
show_weights(BestSeq, importance_type="weight")  #"weight" - how often a feature has been used in making splits

In [ ]:
show_weights(BestSeq, importance_type="gain")

In [ ]:
from sklearn import metrics
## Kpi
print("R2 (explained variance):", round(metrics.r2_score(y_test, predictions), 2))
print("Mean Absolute Perc Error (Σ(|y-pred|/y)/n):", round(np.mean(np.abs((y_test-predictions)/predictions)), 2))
print("Mean Absolute Error (Σ|y-pred|/n):", "{:,.2f}".format(metrics.mean_absolute_error(y_test, predictions)))
print("Root Mean Squared Error (sqrt(Σ(y-pred)^2/n)):", "{:,.2f}".format(np.sqrt(metrics.mean_squared_error(y_test, predictions))))
## residuals
residuals = []
for i, c in zip(y_test, y_pred):
    residuals.append(i - c)

In [ ]:
# SEQ_MD

BestSeqMD = LGBMRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=7, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.1, max_delta_step=0, max_depth=21,
             min_child_weight=25, monotone_constraints='()',
             n_estimators=890, n_jobs=0, num_parallel_tree=1, random_state=7,
             reg_alpha=0.4, reg_lambda=2, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

X_train, X_test, y_train, y_test = train_test_split(Seq_MD, Y, test_size=0.2, random_state=seed)
eval_set = [(X_train, y_train), (X_test, y_test)]
BestSeqMD.fit(X_train, y_train, eval_metric=["mae", "rmse"], eval_set=eval_set, verbose=True, early_stopping_rounds=10)
y_pred = BestSeqMD.predict(X_test)
predictions = [value for value in y_pred]
results = BestSeqMD.evals_result()
epoch = len(results['validation_0']['mae'])
x_axis = range(0, epoch)
# plot log loss
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['mae'], label='Train')
ax.plot(x_axis, results['validation_1']['mae'], label='Test')
ax.legend()
pyplot.ylabel('Mean Absolute Error')
pyplot.title('XGBoost MAE')
pyplot.savefig('XGBoost_MAE_tuned.png')
pyplot.show()
# plot classification error
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['rmse'], label='Train')
ax.plot(x_axis, results['validation_1']['rmse'], label='Test')
ax.legend()
pyplot.ylabel('Root Mean Square Error')
pyplot.title('XGBoost RMSE')
pyplot.savefig('XGBoost_RMSE_tuned.png')
pyplot.show()

perm = PermutationImportance(BestSeqMD, random_state=1).fit(X_test, y_test)
eli5.show_weights(perm, feature_names = X_test.columns.tolist())


from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer()
booster = BestSeqMD.get_booster()
original_feature_names = booster.feature_names
print(booster.get_dump()[0])
booster.feature_names = original_feature_names

In [ ]:
from eli5 import show_weights
show_weights(BestSeqMD, importance_type="cover") #“cover” - the average coverage of the feature.

In [ ]:
# this might be the best one
show_weights(BestSeqMD, importance_type="weight")  #"weight" - how often a feature has been used in making splits

In [ ]:
show_weights(BestSeqMD, importance_type="gain")

In [ ]:
from sklearn import metrics
## Kpi
predictions = [value for value in y_pred]
print("R2 (explained variance):", round(metrics.r2_score(y_test, predictions), 2))
print("Mean Absolute Perc Error (Σ(|y-pred|/y)/n):", round(np.mean(np.abs((y_test-predictions)/predictions)), 2))
print("Mean Absolute Error (Σ|y-pred|/n):", "{:,.2f}".format(metrics.mean_absolute_error(y_test, predictions)))
print("Root Mean Squared Error (sqrt(Σ(y-pred)^2/n)):", "{:,.2f}".format(np.sqrt(metrics.mean_squared_error(y_test, predictions))))
## residuals
residuals = []
for i, c in zip(y_test, y_pred):
    residuals.append(i - c)

In [ ]:
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import mean_absolute_error

scores = []
cv = KFold(n_splits=10, shuffle=True)
fig = plt.figure()
i = 1
for train, test in cv.split(X_train, y_train):
    prediction = model.fit(X_train.iloc[train],
                 y_train.iloc[train]).predict(X_train.iloc[test])
    true = y_train.iloc[test]
    score = mean_absolute_error(true, prediction)
    scores.append(score)
    plt.scatter(prediction, true, lw=2, alpha=0.3,
                label='Fold %d (MAE = %0.2f)' % (i,score))
    i = i+1
plt.plot([min(y_train),max(y_train)], [min(y_train),max(y_train)],
         linestyle='--', lw=2, color='black')
plt.xlabel('Predicted Value')
plt.ylabel('Actual Value')
plt.title('K-Fold Validation')
plt.legend(prop={"size":10}, loc='center left', bbox_to_anchor=(1, 0.5))

plt.show()

In [ ]:
max_error = max(residuals) if abs(max(residuals)) > abs(min(residuals)) else min(residuals)
max_idx = list(residuals).index(max(residuals)) if abs(max(residuals)) > abs(min(residuals)) else list(residuals).index(min(residuals))
max_true, max_pred = y_test.iloc[max_idx], y_pred[max_idx]
print("Max Error:", "{:,.2f}".format(max_error))

In [ ]:
print(y_test.iloc[20] - y_pred[20])

In [ ]:
fig, ax = plt.subplots(nrows=1, ncols=2)
from statsmodels.graphics.api import abline_plot
ax[0].scatter(y_pred, y_test, color="black")
abline_plot(intercept=0, slope=1, color="red", ax=ax[0])
ax[0].vlines(x=max_pred, ymin=max_true, ymax=max_true-max_error, color='red', linestyle='--', alpha=0.7, label="max error")
ax[0].grid(True)
ax[0].set(xlabel="Predicted", ylabel="True", title="Predicted vs True")
ax[0].legend()

## Plot predicted vs residuals
ax[1].scatter(y_pred, residuals, color="red")
ax[1].vlines(x=max_pred, ymin=0, ymax=max_error, color='black', linestyle='--', alpha=0.7, label="max error")
ax[1].grid(True)
ax[1].set(xlabel="Predicted", ylabel="Residuals", title="Predicted vs Residuals")
ax[1].hlines(y=0, xmin=np.min(y_pred), xmax=np.max(y_pred))
ax[1].legend()

plt.show()

In [ ]:
import seaborn as sns
fig, ax = plt.subplots()
sns.distplot(residuals, color="red", hist=True, kde=True, kde_kws={"shade":True}, ax=ax)
ax.grid(True)
ax.set(yticks=[], yticklabels=[], title="Residuals distribution")
plt.savefig("Residues_dist.tiff", dpi=350)
plt.show()

In [ ]:
import shap

In [ ]:
shap_values = shap.Explainer(BestSeqMD).shap_values(X_train)

In [ ]:
shap.summary_plot(shap_values, X_train, plot_type="bar")

In [ ]:
import matplotlib.pyplot as plt
f = plt.figure()
shap.summary_plot(shap_values, X_train)

In [ ]:
import matplotlib.pyplot as plt
f = plt.figure()
shap.summary_plot(shap_values, X_train)

In [ ]:
BestMDMDpocket = LGBMRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=5, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.09, max_delta_step=0, max_depth=91,
             min_child_weight=10, monotone_constraints='()',
             n_estimators=310, n_jobs=0, num_parallel_tree=1, random_state=7,
             reg_alpha=0.2, reg_lambda=5, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)
X_train, X_test, y_train, y_test = train_test_split(MD_MDpocket, Y, test_size=0.2, random_state=seed)
eval_set = [(X_train, y_train), (X_test, y_test)]
BestMDMDpocket.fit(X_train, y_train, eval_metric=["mae", "rmse"], eval_set=eval_set, verbose=True, early_stopping_rounds=10)
y_pred = BestMDMDpocket.predict(X_test)
predictions = [value for value in y_pred]
results = BestMDMDpocket.evals_result()
epoch = len(results['validation_0']['mae'])
x_axis = range(0, epoch)
# plot log loss
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['mae'], label='Train')
ax.plot(x_axis, results['validation_1']['mae'], label='Test')
ax.legend()
pyplot.ylabel('Mean Absolute Error')
pyplot.title('XGBoost MAE')
pyplot.savefig('XGBoost_MAE_tuned.png')
pyplot.show()
# plot classification error
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['rmse'], label='Train')
ax.plot(x_axis, results['validation_1']['rmse'], label='Test')
ax.legend()
pyplot.ylabel('Root Mean Square Error')
pyplot.title('XGBoost RMSE')
pyplot.savefig('XGBoost_RMSE_tuned.png')
pyplot.show()

In [ ]:
from sklearn import metrics
## Kpi
print("R2 (explained variance):", round(metrics.r2_score(y_test, predictions), 2))
print("Mean Absolute Perc Error (Σ(|y-pred|/y)/n):", round(np.mean(np.abs((y_test-predictions)/predictions)), 2))
print("Mean Absolute Error (Σ|y-pred|/n):", "{:,.2f}".format(metrics.mean_absolute_error(y_test, predictions)))
print("Root Mean Squared Error (sqrt(Σ(y-pred)^2/n)):", "{:,.2f}".format(np.sqrt(metrics.mean_squared_error(y_test, predictions))))
## residuals
residuals = []
for i, c in zip(y_test, y_pred):
    residuals.append(i - c)

In [ ]:
BestSeqMDpocket = LGBMRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.4, gamma=3, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.004, max_delta_step=0, max_depth=41,
             min_child_weight=30, monotone_constraints='()',
             n_estimators=640, n_jobs=0, num_parallel_tree=1, random_state=7,
             reg_alpha=0.4, reg_lambda=2, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)
X_train, X_test, y_train, y_test = train_test_split(Seq_MDpocket, Y, test_size=0.2, random_state=seed)
eval_set = [(X_train, y_train), (X_test, y_test)]
BestSeqMDpocket.fit(X_train, y_train, eval_metric=["mae", "rmse"], eval_set=eval_set, verbose=True, early_stopping_rounds=10)
y_pred = BestSeqMDpocket.predict(X_test)
predictions = [value for value in y_pred]
results = BestMDMDpocket.evals_result()
epoch = len(results['validation_0']['mae'])
x_axis = range(0, epoch)
# plot log loss
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['mae'], label='Train')
ax.plot(x_axis, results['validation_1']['mae'], label='Test')
ax.legend()
pyplot.ylabel('Mean Absolute Error')
pyplot.title('XGBoost MAE')
pyplot.savefig('XGBoost_MAE_tuned.png')
pyplot.show()
# plot classification error
fig, ax = pyplot.subplots()
ax.plot(x_axis, results['validation_0']['rmse'], label='Train')
ax.plot(x_axis, results['validation_1']['rmse'], label='Test')
ax.legend()
pyplot.ylabel('Root Mean Square Error')
pyplot.title('XGBoost RMSE')
pyplot.savefig('XGBoost_RMSE_tuned.png')
pyplot.show()
from sklearn import metrics
## Kpi
print("R2 (explained variance):", round(metrics.r2_score(y_test, predictions), 2))
print("Mean Absolute Perc Error (Σ(|y-pred|/y)/n):", round(np.mean(np.abs((y_test-predictions)/predictions)), 2))
print("Mean Absolute Error (Σ|y-pred|/n):", "{:,.2f}".format(metrics.mean_absolute_error(y_test, predictions)))
print("Root Mean Squared Error (sqrt(Σ(y-pred)^2/n)):", "{:,.2f}".format(np.sqrt(metrics.mean_squared_error(y_test, predictions))))
## residuals
residuals = []
for i, c in zip(y_test, y_pred):
    residuals.append(i - c)

In [ ]:
#### LAZY COMPARISON ####
from lazypredict.Supervised import LazyRegressor
from sklearn.model_selection import train_test_split
#
models_lazy = []
datasets = [MDPocket, MD, Seq, Seq_MD, MD_MDpocket, Seq_MDpocket]
for dataset in datasets:
    X_train, X_test, y_train, y_test = train_test_split(dataset, Y, test_size=0.2, random_state=seed)
    reg = LazyRegressor(predictions=True)
    models, predictions = reg.fit(X_train, X_test, y_train, y_test)
    models_lazy.append(models)

In [ ]:
#fit all models

In [ ]:
models_lazy

In [ ]:
import eli5
from eli5.sklearn import PermutationImportance
X_train, X_test, y_train, y_test = train_test_split(Seq, Y, test_size=0.2, random_state=seed)

perm = PermutationImportance(BestSeq, random_state=1).fit(X_test, y_test)
eli5.show_weights(perm, feature_names = X_test.columns.tolist())

In [ ]:
import shap  # package used to calculate Shap values

explainer = shap.TreeExplainer(Best_estimator)
shap_values = explainer.shap_values(X)

In [ ]:
shap.summary_plot(shap_values, X)

In [ ]:
shap.summary_plot(shap_values, X)

In [ ]:
for colu in X:
    shap.dependence_plot(colu, shap_values, X, dot_size=32)

In [ ]:
shap.dependence_plot('VHSE2.1', shap_values, X, dot_size=32)

In [ ]:
explainer = shap.Explainer(Best_estimator)
shap_values = explainer(X_test)

In [ ]:
corr_matrix = pd.DataFrame(shap_values.values,columns=X.columns).corr()
# change this value as needed, if 0.5 does not work for your scenario

In [ ]:
# Display Correlations
ax = sns.heatmap(
    corr_matrix,
    vmin=-1, vmax=1, center=0,
    cmap=sns.diverging_palette(20, 220, n=200),
    square=True
)
ax.set_xticklabels(
    ax.get_xticklabels(),
    rotation=45,
    horizontalalignment='right'
);

#plt.savefig('shap_correlation.png',dpi=300,bbox_inches='tight')

In [ ]:
# shap_values_test
# shap.summary_plot(shap_values, X, max_display=12)
# # plt.savefig("my_importance_plot.pdf", dpi=300, bbox_inches='tight')
# # plt.show()

In [ ]:
# shap.plots.heatmap(shap_values)
# # plt.savefig("my_heatmap_plot.pdf", dpi=300, bbox_inches='tight')
# # plt.show()

In [ ]:
shap.plots.beeswarm(shap_values, max_display=12, show=False)
plt.title("")
plt.ylabel("")
plt.savefig("my_beeswarm_plot.tiff", dpi=350, bbox_inches='tight') # we can save a PDF of the figure if we want
plt.show()

In [ ]:
# shap.plots.scatter(shap_values[:,"halpha"], show=False, dot_size=30, color=shap_values)
# plt.title("halpha dependence plot")
# plt.ylabel("SHAP value for halpha")
# plt.savefig("my_dependence_plot_halpha_high_res.tiff", dpi=350) # we can save a PDF of the figure if we want
# plt.show()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=seed)

explainer = shap.Explainer(Best_estimator)
shap_values_X_test = explainer(X_test)

In [ ]:
shap_interaction = explainer.shap_interaction_values(X_test)

In [ ]:
shap.summary_plot(shap_interaction, X_test)

In [ ]:
mean_shap = np.abs(shap_interaction).mean(0)
df = pd.DataFrame(mean_shap,index=X.columns,columns=X.columns)

# times off diagonal by 2
df.where(df.values == np.diagonal(df),df.values*2,inplace=True)

# display
plt.figure(figsize=(10, 10), facecolor='w', edgecolor='k')
sns.set(font_scale=1.5)
sns.heatmap(df,cmap='coolwarm',annot=True,fmt='.3g',cbar=False)
plt.yticks(rotation=0)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=14)

explainer = shap.Explainer(Best_estimator)
shap_values_X_test = explainer(X_test)

shap.plots.heatmap(shap_values_X_test, show=False)
plt.savefig("my_heatmap_plot_test.tiff", dpi=350, bbox_inches='tight')
plt.show()

In [ ]:
shap.plots.beeswarm(shap_values_X_test, max_display=12, show=False)
plt.title("")
plt.ylabel("")
plt.savefig("my_beeswarm_plot_X_test.pdf", dpi=350, bbox_inches='tight') # we can save a PDF of the figure if we want
plt.show()

In [ ]:
shap.summary_plot(shap_values, X_test, max_display=12, show=False)
plt.title("")
plt.ylabel("")
plt.savefig("my_beeswarm_plot_X_test.pdf", dpi=350, bbox_inches='tight') # we can save a PDF of the figure if we want
plt.show()

In [ ]:
for file in os.listdir():
    print(file )